spring.application.name=cryptosim-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/cryptosim
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

coingecko.api.base-url=https://api.coingecko.com/api/v3/
coingecko.api.key=${COINGECKO_API_KEY}